#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs..#
export LC_ALL=en_GB.UTF-8
export GOPATH=$HOME/workspace
export PATH=$PATH:$GOPATH/bin:/usr/local/opt/go/libexec/bin

# added by travis gem
[ -f /Users/aleherse/.travis/travis.sh ] && source /Users/aleherse/.travis/travis.sh
if [ -f /Users/aleherse/Workspace/tuprogramaelectoral/artifacts/aliases ]; then
    export TPE_PATH=/Users/aleherse/Workspace/tuprogramaelectoral
    source /Users/aleherse/Workspace/tuprogramaelectoral/artifacts/aliases
fi
if [ -f /Users/aleherse/Workspace/polis/artifacts/aliases ]; then
    export POLIS_PATH=/Users/aleherse/Workspace/polis
    source /Users/aleherse/Workspace/polis/artifacts/aliases
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

cd ~/workspace

# Added AWS credentials
if [ -f ~/.credentials/load.zsh ]; then
    source ~/.credentials/load.zsh 
fi

# Added App Engine 
if [ -f /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc ]; then
    source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
    source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
fi
